### ISSUE TITLE
Query AWS meta-data to determine AWS_REGION if not set

### ISSUE THREAD

**Issue by frittentheke** [atongen/ec2hosts#1]
Thank you very much for this awesome tool!

I if may make a feature request ...

AWS provides ec2metadata (https://docs.aws.amazon.com/sdk-for-go/api/aws/ec2metadata/) to determine in which region we are running? Sure it should be possible to still configure this variable statically, but I believe this is then one less thing to configure and it allows the configuration to be even simpler, no matter in what region ec2hosts is used.

I suggested a similar thing for the Kubernetes Cluster-Autoscaler ... https://github.com/kubernetes/autoscaler/issues/1208 which lead to PR https://github.com/kubernetes/autoscaler/pull/1288. Maybe you could simply use the same approach?

**Comment by atongen** [comment]
Thanks for the tip! This should be addressed in version [0.1.6](https://github.com/atongen/ec2hosts/releases/tag/0.1.6). Let me know if there are any issues!
